## Numpy

Импортировать NumPy под именем np

In [2]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [2]:
vec = np.zeros(10, dtype=int)

display(vec)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Создать вектор размера 10, заполненный единицами

In [3]:
vec = np.ones(10)

display(vec)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Создать вектор размера 10, заполненный числом 2.5

In [4]:
vec = np.repeat(2.5, 10)

display(vec)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [5]:
vec = np.where(np.arange(10)==4, np.ones(10, dtype=int), np.zeros(10, dtype=int))

display(vec)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

Развернуть вектор (первый становится последним)

In [6]:
vec = np.random.random(10)

display(vec)

vec = vec[::-1]

display(vec)

array([0.07055436, 0.05073166, 0.69478393, 0.17241628, 0.45767495,
       0.44131516, 0.13655278, 0.70097031, 0.09809925, 0.33032654])

array([0.33032654, 0.09809925, 0.70097031, 0.13655278, 0.44131516,
       0.45767495, 0.17241628, 0.69478393, 0.05073166, 0.07055436])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [7]:
mat = np.arange(9, dtype=int).reshape((3, 3))

display(mat)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [8]:
vec = np.array([1,2,0,0,4,0])

indices = np.nonzero(vec)[0]

display(indices)

array([0, 1, 4])

Создать 3x3 единичную матрицу

In [9]:
mat = np.ones(9).reshape((3, 3))

display(mat)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Создать массив 3x3x3 со случайными значениями

In [10]:
arr = np.random.random((3,3,3))

display(arr)

array([[[0.51651712, 0.48440167, 0.3645365 ],
        [0.29194915, 0.68931728, 0.29149552],
        [0.12334267, 0.85217909, 0.25648044]],

       [[0.49205076, 0.2978227 , 0.73686813],
        [0.98573123, 0.24937782, 0.48652074],
        [0.5416093 , 0.9359859 , 0.5007415 ]],

       [[0.5008218 , 0.8360567 , 0.33828396],
        [0.61472384, 0.02556472, 0.29595658],
        [0.78337343, 0.00944115, 0.38434813]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [11]:
vec = np.random.random((30, 1))

s = np.mean(vec)

display(s)

0.5781455262510111

Перемножить матрицы 5x3 и 3x2

In [12]:
a = np.random.random((5, 3))
b = np.random.random((3, 2))
mat = a.dot(b)

display(mat)

array([[0.73813997, 1.10096837],
       [0.31490491, 0.33460246],
       [0.61810756, 1.06346596],
       [0.81649335, 1.38671029],
       [0.98742211, 1.36075959]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [13]:
vec = np.linspace(0, 1, 12)[1:-1]

display(vec)

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

Заменить максимальный элемент на ноль

In [14]:
arr = np.random.random((10, ))

display(arr)

arr[np.unravel_index(arr.argmax(), arr.shape)] = 0

display(arr)

array([0.6622614 , 0.31886446, 0.33373433, 0.32413621, 0.31378325,
       0.17759501, 0.44794004, 0.93387146, 0.9307095 , 0.46317659])

array([0.6622614 , 0.31886446, 0.33373433, 0.32413621, 0.31378325,
       0.17759501, 0.44794004, 0.        , 0.9307095 , 0.46317659])

Преобразовать массив из float в int

In [15]:
arr = np.array([1.5, 2.5]).astype(int)

display(arr)

array([1, 2])

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [5]:
from numpy import arange, tile, ix_
from numpy.linalg import norm

n = 10
a = np.random.random([2, n])

display(a)

with_fixed_first_argument = a[ix_([0, 1], arange(n).repeat(n))]
with_fixed_second_argument = a[ix_([0, 1], tile(arange(n), n))]
arr = norm(with_fixed_first_argument - with_fixed_second_argument, axis=0).reshape(n, n)

display(arr)

array([[0.15823617, 0.86242687, 0.63197003, 0.18335831, 0.98339691,
        0.59568415, 0.46176851, 0.39024253, 0.4197022 , 0.27365898],
       [0.48358517, 0.3974869 , 0.65780897, 0.06897353, 0.74724488,
        0.31267089, 0.89407923, 0.44530296, 0.55450978, 0.91052208]])

array([[0.        , 0.7094346 , 0.50475509, 0.41537205, 0.86626017,
        0.46965139, 0.51052644, 0.23514352, 0.27091472, 0.44226411],
       [0.7094346 , 0.        , 0.34767504, 0.75435744, 0.370087  ,
        0.27990255, 0.63806822, 0.47459924, 0.46974602, 0.78093068],
       [0.50475509, 0.34767504, 0.        , 0.74025648, 0.36262878,
        0.34704029, 0.29119099, 0.32185554, 0.23606854, 0.43846406],
       [0.41537205, 0.75435744, 0.74025648, 0.        , 1.04886309,
        0.47895824, 0.87081092, 0.42944723, 0.5400036 , 0.84637945],
       [0.86626017, 0.370087  , 0.36262878, 1.04886309, 0.        ,
        0.58238796, 0.54190083, 0.66558323, 0.59573361, 0.72827699],
       [0.46965139, 0.27990255, 0.34704029, 0.47895824, 0.58238796,
        0.        , 0.59663143, 0.24453534, 0.29909146, 0.67906278],
       [0.51052644, 0.63806822, 0.29119099, 0.87081092, 0.54190083,
        0.59663143, 0.        , 0.45444043, 0.34216514, 0.18882681],
       [0.23514352, 0.47459924, 0.3218555

Случайно расположить p элементов в 2D массив

In [17]:
import math

p = 17
arr = np.random.random((p, ))

display(arr)

width = math.trunc(math.sqrt(p))
height = math.ceil(p * 1.0 / width)
np.random.shuffle(arr)
arr = np.array(list(arr) + (width * height - p) * [None]).reshape(width, height)   

display(arr)

array([5.53629186e-01, 1.48276209e-01, 5.22615458e-01, 9.34726830e-01,
       5.37348596e-01, 1.33342166e-01, 1.10376551e-01, 3.15083037e-01,
       7.63475216e-01, 9.06783308e-04, 4.22081401e-01, 7.76315608e-01,
       3.79933931e-01, 7.19297441e-01, 4.58872074e-01, 5.07679147e-01,
       9.33176749e-01])

array([[0.45887207401457963, 0.3799339306853753, 0.9347268300209344,
        0.0009067833076179532, 0.5536291859876653],
       [0.315083036965921, 0.5226154584789235, 0.719297441090565,
        0.11037655084654419, 0.42208140149979256],
       [0.7763156080190767, 0.5076791466074462, 0.7634752157745421,
        0.9331767488586106, 0.133342165530134],
       [0.5373485956129747, 0.14827620866628966, None, None, None]],
      dtype=object)

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [6]:
from functools import reduce
a = np.array([1, 2, 3, 4, 5])
arr = reduce(lambda acc, val: np.hstack([acc, np.zeros(3), val]), a)

display(arr)

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

Найти наиболее частое значение в массиве

In [19]:
arr = np.random.randint(1, 4, size=10)

display(arr)

values, counts = np.unique(arr, return_counts=True)

display(values[np.argmax(counts)])

array([1, 2, 3, 1, 1, 3, 1, 2, 2, 2])

1

Найти n наибольших значений в массиве

In [20]:
a = np.random.randint(1, 42, size=42)
n = 3

display(a)

arr = np.sort(a)[-n:][::-1]

display(arr)

array([21,  1, 16, 22, 20, 10, 21, 24,  4, 40, 39, 14, 38, 28, 24,  9, 27,
       35,  8, 30, 10, 35,  5, 16, 23,  8,  5,  2, 35, 19, 34, 31, 31,  2,
       34, 12, 19, 41, 38, 37,  3,  7])

array([41, 40, 39])

## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [9]:
import pandas as pd

In [22]:
food = pd.read_csv('en.openfoodfacts.org.products.tsv', sep='\t')

/home/alexander/.virtualenvs/otus-ds/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Посмотреть первые 5 записей

In [23]:
display(food.head(5))

code                                                url  \
0   3087  http://world-en.openfoodfacts.org/product/0000...   
1   4530  http://world-en.openfoodfacts.org/product/0000...   
2   4559  http://world-en.openfoodfacts.org/product/0000...   
3  16087  http://world-en.openfoodfacts.org/product/0000...   
4  16094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity  ... fruits-vegetables-nuts_100g  \
0          NaN      1kg  ...                         NaN   
1          NaN      NaN  ...                         NaN   
2          NaN      NaN  ...                         NaN   
3          NaN      NaN  ...                         NaN   
4          NaN      NaN  ...                         NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?

In [24]:
display(food.shape[0])

356027

Сколько столбцов в наборе данных?

In [25]:
display(food.shape[1])

163

Напечатайте все названия столбцов

In [26]:
display(food.columns)

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

Какое название у 105 столбца?

In [27]:
display(food.columns[104])

'-glucose_100g'

Какой тип наблюдений в 105 столбце?

In [28]:
display(food.dtypes[104])

dtype('float64')

Как проиндексирован набор данных?

In [29]:
display(food.index)

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [30]:
display(food.iloc[18]['product_name'])

'Lotus Organic Brown Jasmine Rice'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [11]:
chipo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep='\t')
chipo['item_price'] = chipo['item_price'].str.replace('$', '').astype(float)

Как много продуктов стоят более чем $10.00?

In [32]:
display(chipo[chipo['item_price'] > 10].size)

5650

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [33]:
display(chipo[chipo['item_price'] > 10][['item_name', 'item_price']])

item_name  item_price
4           Chicken Bowl       16.98
5           Chicken Bowl       10.98
7          Steak Burrito       11.75
13          Chicken Bowl       11.25
23       Chicken Burrito       10.98
39         Barbacoa Bowl       11.75
42          Chicken Bowl       11.25
43         Steak Burrito       11.75
45       Chicken Burrito       10.98
52       Chicken Burrito       10.98
57        Veggie Burrito       11.25
58         Barbacoa Bowl       11.75
62           Veggie Bowl       11.25
68       Chicken Burrito       10.98
79    Chicken Soft Tacos       11.25
90            Steak Bowl       11.75
91            Steak Bowl       11.75
93      Carnitas Burrito       11.75
97         Carnitas Bowl       11.75
123         Chicken Bowl       11.25
130     Barbacoa Burrito       11.75
134      Chicken Burrito       10.98
135   Chicken Salad Bowl       22.50
136        Barbacoa Bowl       11.75
138         Chicken Bowl       11.25
140         Chicken Bowl       11.25
142         Chicken Bowl       11.25
143          Veggie Bowl       11.25
144     Barbacoa Burrito       11.75
147        Steak Burrito       11.48
...                  ...         ...
4504       Carnitas Bowl       11.75
4506        Chicken Bowl       11.25
4510       Barbacoa Bowl       11.49
4518          Steak Bowl       11.75
4521     Chicken Burrito       11.25
4523  Steak Crispy Tacos       11.75
4533     Chicken Burrito       11.25
4540        Chicken Bowl       11.25
4553        Chicken Bowl       11.25
4554  Steak Crispy Tacos       11.75
4556     Chicken Burrito       11.25
4559     Chicken Burrito       11.25
4561  Chicken Salad Bowl       17.50
4564        Chicken Bowl       11.25
4576        Chicken Bowl       11.25
4580  Chicken Salad Bowl       11.25
4586        Chicken Bowl       11.25
4587        Chicken Bowl       11.25
4589        Chicken Bowl       11.25
4590        Chicken Bowl       11.25
4592    Barbacoa Burrito       11.75
4593       Carnitas Bowl       11.75
4594       Barbacoa Bowl       11.75
4607       Steak Burrito       11.75
4608      Veggie Burrito       11.25
4610       Steak Burrito       11.75
4611      Veggie Burrito       11.25
4617       Steak Burrito       11.75
4618       Steak Burrito       11.75
4619  Chicken Salad Bowl       11.25

[1130 rows x 2 columns]

Отсортировать по имени предмета

In [34]:
display(chipo.sort_values(by='item_name'))

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
4527      1800         1  6 Pack Soft Drink   
4522      1798         1  6 Pack Soft Drink   
3806      1525         1  6 Pack Soft Drink   
2389       949         1  6 Pack Soft Drink   
3132      1248         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
639        264         1  6 Pack Soft Drink   
1026       422         1  6 Pack Soft Drink   
...        ...       ...                ...   
2996      1192         1       Veggie Salad   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
1694       686         1       Veggie Salad   
2756      1094         1       Veggie Salad   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description  item_price  
3389                                        [Diet Coke]       12.98  
341                                         [Diet Coke]        6.49  
1849                                             [Coke]        6.49  
1860                                        [Diet Coke]        6.49  
2713                                             [Coke]        6.49  
3422                                             [Coke]        6.49  
553                                         [Diet Coke]        6.49  
1916                                        [Diet Coke]        6.49  
1922                                             [Coke]        6.49  
1937                                        [Diet Coke]        6.49  
3836                                             [Coke]        6.49  
298                                            [Sprite]        6.49  
1976                                        [Diet Coke]        6.49  
1167                                             [Coke]        6.49  
3875                                     

Сколько было заказано самого дорогого предмета?

In [16]:
most_expensive_item_name = chipo.nlargest(1, 'item_price')['item_name'].iloc[0]

chipo[chipo['item_name'] == most_expensive_item_name]['quantity'].sum()

130

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [15]:
chipo[chipo['item_name'] == 'Veggie Salad Bowl']['quantity'].sum()

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [37]:
display(chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)].size)

100